<?php

namespace CategorieBundle\Repository;

/**
 * idRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class idRepository extends \Doctrine\ORM\EntityRepository
{
}
