<?php

namespace EtudiantBundle\Repository;

/**
 * IdERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdERepository extends \Doctrine\ORM\EntityRepository
{
}
